spring:
  name: ott
  profiles:
    include: private
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: private
  h2:
    console:
      enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    prefix: classpath:/tamplates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: brV+BhkMf5IquaNow0zQByH/gzSjfNUOzTtkC5T3e3A=

api:
  contents:
    kobis:
      domain: http://kobis.or.kr
      key: 82ca741a2844c5c180a208137bb92bd7
      uris:
        movie-list: /kobisopenapi/webservice/rest/movie/searchMovieList.json
        movie-detail-info : /kobisopenapi/webservice/rest/movie/searchMovieInfo.json
  user:
    kakao:
      auth-domain: https://kauth.kakao.com
      api-domain: https://kapi.kakao.com
      key: eb494412fc82cf6b33420efbdfa9f3cb
      redirect-uri: http://localhost:8080/login/auth
      uris:
        user-info: /v2/user/me
        authorize: /oauth/authorize
        token: /oauth/token


